### ISSUE TITLE
select * queries stop working when you alter table (add 2 new columns)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/gocql#261] opened 2024-09-13 09:04 UTC
Same apache issue: https://github.com/apache/cassandra-gocql-driver/issues/1056
Original core issue: https://github.com/scylladb/scylla-enterprise/issues/4636

### What version of ScyllaDB or Cassandra are you using?
2024.1

### What version of ScyllaDB Gocql driver are you using?
1.14.0
(but happens in older versions too)

### What did you do?
have multiple pods with gocql clients running `select * from ...`
then from external client run `ALTER` and add 2 new columns to table

`select *` queries will start failing
until clients in pods are restarted

**Comment by tarzanek** [comment] 2024-09-13 09:05
ref https://github.com/apache/cassandra-gocql-driver/issues/1056

**Comment by tarzanek** [comment] 2024-09-13 09:33
if we change the the select *  queries into select col1, col2 then it works after alter

**Comment by tarzanek** [comment] 2024-09-13 10:01
ref https://github.com/scylladb/scylla-enterprise/issues/4636

**Comment by sylwiaszunejko** [comment] 2024-09-25 08:43
I managed to reproduce the issue with this code:
For running SELECT * queries:
```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gocql/gocql"
)

func main() {
	// Create a cluster connection
	cluster := gocql.NewCluster("127.0.0.2") // Replace with actual IP(s) of Scylla nodes
	cluster.Keyspace = "testkeyspace"
	cluster.Consistency = gocql.Quorum
	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalf("Unable to connect to cluster: %v\n", err)
	}
	defer session.Close()

	// Continuous loop to run SELECT * queries
	for {
		fmt.Println("FOR")
		// Running SELECT * on the table
		iter := session.Query(`SELECT * FROM testtable`).Iter()
		row := make(map[string]interface{})
		for iter.MapScan(row) {
			fmt.Println("Row: ", row)
			row = make(map[string]interface{})
		}
		if err := iter.Close(); err != nil {
			log.Printf("Error in query: %v\n", err)
		}

		// Delay between queries
		time.Sleep(2 * time.Second)
	}
}
```
For adding new columns
```go
package main

import (
	"log"

	"github.com/gocql/gocql"
)

func main() {
	// Create a cluster connection
	cluster := gocql.NewCluster("127.0.0.2") // Replace with actual IP(s) of Scylla nodes
	cluster.Keyspace = "testkeyspace"
	cluster.Consistency = gocql.Quorum
	session, err := cluster.CreateSession()
	if err != nil {
		log.Fatalf("Unable to connect to cluster: %v\n", err)
	}
	defer session.Close()

	// Alter the table to add two new columns
	err = session.Query(`ALTER TABLE testtable ADD new_column1 text`).Exec()
	if err != nil {
		log.Fatalf("Failed to alter table: %v\n", err)
	}

	err = session.Query(`ALTER TABLE testtable ADD new_column2 text`).Exec()
	if err != nil {
		log.Fatalf("Failed to alter table: %v\n", err)
	}

	log.Println("Successfully added two new columns")
}
```
The result of running SELECT * in a loop looks like that:
```
Row:  map[id:507aa0f7-c9d6-4d66-9bf7-165aee3db10d name:Bob]
Row:  map[id:dcb6f2be-757a-4e14-bd9b-44ed7c726b01 name:Sylwia]
Row:  map[id:12ff47fc-db2a-4d6a-85b8-77777b51a2f3 name:Alice]
FOR
Row:  map[id:507aa0f7-c9d6-4d66-9bf7-165aee3db10d name:Bob new_column1:]
Row:  map[id:dcb6f2be-757a-4e14-bd9b-44ed7c726b01 name:Sylwia new_column1:]
Row:  map[id:12ff47fc-db2a-4d6a-85b8-77777b51a2f3 name:Alice new_column1:]
FOR
Row:  map[id:507aa0f7-c9d6-4d66-9bf7-165aee3db10d name:Bob new_column1: new_column2:]
Row:  map[id:dcb6f2be-757a-4e14-bd9b-44ed7c726b01 name:Sylwia new_column1: new_column2:]
Row:  map[id:12ff47fc-db2a-4d6a-85b8-77777b51a2f3 name:Alice new_column1: new_column2:]
FOR
Row:  map[id:507aa0f7-c9d6-4d66-9bf7-165aee3db10d name:Bob]
Row:  map[id:00000000-0000-0000-0000-000000000000 name:]
Row:  map[id:dcb6f2be-757a-4e14-bd9b-44ed7c726b01 name:Sylwia]
FOR
Row:  map[id:507aa0f7-c9d6-4d66-9bf7-165aee3db10d name:Bob new_column1:]
Row:  map[id:00000000-0000-0000-0000-000000000000 name:ܶ�uzN��D�|rk new_column1:Sylwia]
Row:  map[id:00000000-0000-0000-0000-000000000000 name: new_column1:�G��*Mj��ww{Q��]
```
The first set of rows is what the table looked like before running any code.

**Comment by sylwiaszunejko** [comment] 2024-09-30 13:25
Unfortunately there are more cases when the behavior is broken, due to that we have decided to change default behavior to disable skipping metadata, until the issue with invalidating prepared statements when altering table/column is fixed on the server side (https://github.com/scylladb/scylladb/issues/20860).
The PR with the change is merged: https://github.com/scylladb/gocql/pull/283.

**Closed by sylwiaszunejko** 2024-09-30 13:25 UTC
Labels: triage
