### ISSUE TITLE
Performance issues when switched from gocql/gocql to scylladb/gocql

### ISSUE THREAD

**Issue by eagle1305** [scylladb/gocql#43] opened 2020-04-30 09:56 UTC
Please answer these questions before submitting your issue. Thanks!

### What version of Scylla or Cassandra are you using?
Scylla : Version : 3.2

### What version of Gocql are you using?
latest

### What did you do?
Migrated from gocql/gocql to scylladb/gocql

### What did you expect to see?
Performance improvements. Less non-token aware queries.

### What did you see instead?
1. Non-token aware queries did not reduce to zero instead remained almost same although there was a visible decrement in cross-shard queries.
2. Total requests served per coordinator had increased.
3. Total requests(Scylla CQL optimisation) had also increased.
4. Latency on one of the node was especially very high.
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
- output of `SELECT peer, rpc_address FROM system.peers`
- rebuild your application with the `gocql_debug` tag and post the output

**Comment by gunnsth** [comment] 2020-09-22 08:05
I am running into a possibly related issue with a lot of open file descriptors.  I am loading a bunch of data periodically to a Cluster of 3 nodes with multiple go routines through a single session.
 
For example, when I run lsof every few seconds, the number of connections fluctuate wildly when using scylladb/gocql:
```
# lsof -n | grep 9042 | wc -l
1000
# lsof -n | grep 9042 | wc -l
4847
# lsof -n | grep 9042 | wc -l
4585
# lsof -n | grep 9042 | wc -l
6035
# lsof -n | grep 9042 | wc -l
1901
# lsof -n | grep 9042 | wc -l
1725
# lsof -n | grep 9042 | wc -l
1500
# lsof -n | grep 9042 | wc -l
1250
# lsof -n | grep 9042 | wc -l
2420
# lsof -n | grep 9042 | wc -l
8491
```

where as for direct drop in replacement with gocql/gocql:
```
# lsof -n | grep 9042 | wc -l
252
# lsof -n | grep 9042 | wc -l
308
# lsof -n | grep 9042 | wc -l
308
# lsof -n | grep 9042 | wc -l
308
# lsof -n | grep 9042 | wc -l
308
# lsof -n | grep 9042 | wc -l
308
# lsof -n | grep 9042 | wc -l
280
```
with the exact same parameters.

Even jumping up to 50952.. pretty wild numbers, and my connections graph
![image](https://user-images.githubusercontent.com/50777/93857593-59d51c80-fcaa-11ea-8f73-3bd9853ba293.png)

**Comment by mmatczuk** [comment] 2020-09-23 10:40
Hi @gunnsth,
a new version v1.4.1 fixes a connection leak on session close, deadlock on connection close when closing fails, and improves logging so please use that one. Would you mind building and running your reproducer with `-tags gocql_debug` and share the driver logs here?

My working theory is that you are hitting a case where:
1. the pool is not yet fully filled i.e. not all shards have a connection - in that case it can keep up to 10 times the nr of shards of excessive connections per host
1. the session is closed so you are hitting the leak where we do not close the excessive connections when session is closed - fixed in v.1.4.1

Waiting for your feedback.

**Comment by gunnsth** [comment] 2020-09-25 16:09
@mmatczuk I tried again with the newest master and the connection issue seems to be fixed.  Seems stable now.

**Comment by gunnsth** [comment] 2020-09-29 16:49
@mmatczuk What is the expected number of connections?  For example if I have `NumConns = 2` does that still mean that we will be getting 2 connections to each node specified as a host (gocql.NewCluster)?  Or is that 2 per shard?  Did not find a clear documentation on this. I have NumConns = 2 but am getting a total of ~300 connections per application (3 hosts).
It is stable now, but the number of connections is a bit higher than I expected.

**Comment by mmatczuk** [comment] 2020-10-02 14:16
`NumConns` has no effect when using the shard aware mode i.e. driver is [properly configured](https://github.com/scylladb/gocql#configuration). It is ignored and the driver would read it from Scylla.

You should have nr. of Scylla nodes * nr. of shards * nr. of clients. In other words each client connects to every shard in the cluster.

**Comment by mmatczuk** [comment] 2020-10-29 21:16
Any updates @gunnsth? 1.4.3 should further improve things for you since it has 393f0c9.

**Comment by gunnsth** [comment] 2020-10-29 22:01
@mmatczuk From our standpoint this has been fixed, the behavior is stable now and the number of connections makes sense with respect to your description above.  Might be good to add a comment on `NumConns` regarding how it works in shard-aware mode, or at least I did not see notice it in the documentation when working on this.  Might have missed it.

**Closed** 2022-02-18 10:17 UTC
